import * as admin from 'firebase-admin';

admin.initializeApp();

export { setUserClaims } from './triggers/users';
export { onSchoolChildUpdatedClearClassIfInactive, onSchoolChildClassAssignmentChanged, onSchoolChildCreatedWithClass } from './triggers/children';
export { onSchoolClassTeacherAssigned, onSchoolClassCreatedWithTeacher } from './triggers/classes';
export { onReportCreated } from './triggers/reports';
export { onDailyCommunicationCreated, onAnnouncementCreated } from './triggers/announcements';
export { sendAnnouncementReminders } from './schedulers/announcementReminders';
export { onChatMessageCreated } from './triggers/chat';
export { syncClaims, selectActiveRole, saveFcmToken } from './callables/account';
export { getOrCreateChat } from './callables/chat';
export { createSchoolWithPrincipal, adminSetSchoolSuspended } from './callables/schools';
export { processSchoolDeletionJobs } from './schedulers/schoolDeletion';
export { adminQueueSchoolDeletion, adminCancelSchoolDeletion } from './callables/schoolDeletion';
export { adminInvitePrincipal, inviteSchoolPrincipal, adminInviteSuperAdmin } from './callables/invites/send';
export { resendPrincipalInvite, resendSuperAdminInvite } from './callables/invites/resend';
export { resendSchoolInvite } from './callables/invites/resendSchool';
export { deleteInviteToken, listPrincipalSchoolInvites, peekInviteToken } from './callables/invites/manage';
export { acceptInviteToken } from './callables/invites/accept';
export { createOrUpdateQrCode, regenerateQrCode, generatePersonalisedQrsFromCsv } from './callables/qr';
export { joinSchoolInfo, createJoinSession } from './http/joinInfo';
export { registerParentViaQr } from './http/register';
export { joinSchoolClasses, uploadChildPhoto, trackAnalyticsEvent } from './http/joinMisc';
export { approveOrRejectParent } from './callables/parentApproval';
export { recordParentFirstLogin, completeParentOnboardingTour, getParentHomeBootstrap, addSiblingChild, recordFirstPhotoViewed } from './callables/parentApp';
export { principalInviteTeacher, principalInviteParent } from './callables/staffInvites';
export { createTeacher, updateTeacher, principalDeleteTeacher } from './callables/teachers';
export { createSuperAdmin, removeSuperAdmin } from './callables/admins';
export { checkParentEmail, inviteParentToChild } from './callables/parentLinks';
export { updateParent, principalRemoveParentFromChild, principalDeleteParent } from './callables/parentAccounts';
export { updateChildProfileByParent, updateChildProfileByTeacher, updateParentProfile, updateTeacherNotificationPreferences } from './callables/profiles';
export { sendEventReminders } from './schedulers/eventReminders';
